name: KHB Live Tests
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'   # كل يوم الساعة 10 صباحًا بتوقيت الأردن
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g newman newman-reporter-htmlextra
      - run: newman run KHB_LIVE_DO_NOT_UPDATE______postman_collection.json -e KHBLIVE.postman_environment.json --reporters "cli,htmlextra" --reporter-htmlextra-export khb-report.html
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: khb-report
          path: khb-report.html


